"""把 TTF 字体读成 base64，生成 src/embeddedFonts.ts。

跑一次：
    .venv/bin/python remotion/embed_fonts.py

产物 src/embeddedFonts.ts 是稳定的（除非换字体），可以提交进 git。

为啥需要：Remotion 渲染时多个 Chromium worker 并发加载本地 HTTP 上的 4MB 字体，
高负载下个别 worker 加载会卡 180s+ 导致 delayRender 超时。
内嵌成 data: URL 后字体跟代码一起进 webpack bundle，加载从磁盘走，永不超时。
"""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FONTS_DIR = ROOT / "public" / "fonts"
OUT = ROOT / "src" / "embeddedFonts.ts"

FONTS_ROOT = Path(__file__).resolve().parent.parent / "fonts"

FONTS = {
    "FONT_SMILEY_SANS": FONTS_DIR / "SmileySans-Oblique.ttf",
    "FONT_PANGMEN": FONTS_DIR / "PangMen.ttf",
    # 设计字体
    "FONT_FANGYUAN": FONTS_ROOT / "AlimamaFangYuanTi-Heavy.ttf",     # 圆体可爱（vlog）
    "FONT_ZHUSHI": FONTS_ROOT / "YangRenDongZhuShi.ttf",             # 竹石毛笔感（中式）
    "FONT_PUHUITI": FONTS_ROOT / "AlibabaPuHuiTi-3-105-Heavy.ttf",   # 现代黑体重
    "FONT_GAODUANHEI": FONTS_ROOT / "ZcoolGaoduanhei.ttf",           # 站酷高端黑（精致）
    "FONT_SHUHEITI": FONTS_ROOT / "AlimamaShuHeiTi.ttf",             # 书黑（雅致）
}


def main() -> None:
    parts: list[str] = [
        "// Auto-generated by embed_fonts.py — do not edit by hand.\n",
        "// 把字体内嵌成 data: URL 避免 Remotion 渲染时 HTTP 字体超时。\n\n",
    ]
    for name, path in FONTS.items():
        if not path.exists():
            raise FileNotFoundError(f"字体缺失: {path}")
        size_mb = path.stat().st_size / 1024 / 1024
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        parts.append(
            f"// {path.name} ({size_mb:.2f} MB)\n"
            f'export const {name} = "data:font/ttf;base64,{b64}";\n\n'
        )
        print(f"[ok] {name}: {path.name} ({size_mb:.2f} MB → {len(b64) / 1024 / 1024:.2f} MB base64)")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"[done] 写出 {OUT}")


if __name__ == "__main__":
    main()
