"""把一个视频转录 + 选择性配图 + 章节 + 标题 + hashtag，写到 src/realCues.ts。

策略：
- 字幕：得意黑白字 + 半透明黑底，关键词高亮
- 图片：LLM 从字幕里挑 2-4 句关键句配图，右上角小窗
- 章节：DeepSeek 切 3-5 段，顶部章节进度条
- 片头：≤6 字大标题，前 1 秒淡入淡出
- Hashtag：基于标题，顶部右上角小贴

用法:
    .venv/bin/python remotion/make_cues.py "/path/to/video.mp4"
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT))
load_dotenv(PROJECT_ROOT / ".env")

from app.transcribe import transcribe  # noqa: E402
from app.imagery import pick_image_cues, search_pexels, download  # noqa: E402
from app.llm import extract_chapters, generate_title  # noqa: E402

FPS = 30
COVER_FRAMES = 1  # 跟 Python pipeline 一致：仅占 1 帧用作缩略图


def video_duration_seconds(path: Path) -> float:
    out = subprocess.check_output(
        [
            "ffprobe", "-v", "error", "-show_entries", "format=duration",
            "-of", "default=nokey=1:noprint_wrappers=1", str(path),
        ],
        text=True,
    )
    return float(out.strip())


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("用法: python make_cues.py <video>")
    src = Path(sys.argv[1]).expanduser().resolve()
    if not src.exists():
        sys.exit(f"视频不存在: {src}")

    duration = video_duration_seconds(src)
    duration_frames = int(round(duration * FPS))

    print(f"[1/7] 转录 {src.name} (约 {duration:.1f}s)...")
    segments, lang = transcribe(src)
    print(f"      检测到语言: {lang}, 共 {len(segments)} 段")
    texts = [t for _, _, t in segments]
    transcript_joined = "".join(texts)

    print("[2/7] DeepSeek 生成 ≤6 字爆款标题...")
    title, title_src = generate_title(transcript_joined)
    print(f"      标题: 「{title}」 (来源: {title_src})")
    hashtag = f"#{title}"

    print("[3/7] DeepSeek 切章节...")
    chapters_raw, ch_src = extract_chapters(segments, duration)
    print(f"      切了 {len(chapters_raw)} 段 (来源: {ch_src})")
    for c in chapters_raw:
        print(f"         {c['start']:5.1f}s-{c['end']:5.1f}s  {c['title']}")
    chapters = [
        {
            "title": c["title"],
            "startFrame": max(0, int(round(c["start"] * FPS))),
            "endFrame": min(duration_frames, int(round(c["end"] * FPS))),
        }
        for c in chapters_raw
    ]

    print("[4/7] DeepSeek 挑选关键句配图...")
    picks = pick_image_cues(texts)
    for idx, kw in picks:
        print(f"      ★ #{idx} 「{texts[idx]}」 → {kw!r}")

    print("[5/7] Pexels 搜图 + 下载...")
    images_dir = ROOT / "public" / "images"
    if images_dir.exists():
        shutil.rmtree(images_dir)
    images_dir.mkdir(parents=True)

    image_for_idx: dict[int, str] = {}
    for idx, kw in picks:
        if not kw:
            continue
        url = search_pexels(kw)
        if not url:
            print(f"      #{idx} {kw!r} → 无结果")
            continue
        dst = images_dir / f"{idx:02d}.jpg"
        if download(url, dst):
            print(f"      #{idx} {kw!r} → {dst.name} ✓")
            image_for_idx[idx] = f"images/{dst.name}"

    cues = []
    for i, (start, end, text) in enumerate(segments):
        cues.append(
            {
                "startFrame": max(0, int(round(start * FPS))),
                "endFrame": min(duration_frames, int(round(end * FPS))),
                "text": text,
                "imageSrc": image_for_idx.get(i),
            }
        )

    print("[6/8] 拷视频 → remotion/public/source.mp4")
    public_dir = ROOT / "public"
    public_dir.mkdir(exist_ok=True)
    dst_video = public_dir / "source.mp4"
    shutil.copyfile(src, dst_video)

    print("[7/8] 抽封面背景帧 (取 30% 处)...")
    cover_bg = public_dir / "cover_bg.jpg"
    cover_t = max(0.5, duration * 0.3)
    subprocess.run(
        [
            "ffmpeg", "-y", "-ss", f"{cover_t:.3f}", "-i", str(dst_video),
            "-frames:v", "1", "-q:v", "2", str(cover_bg),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    cover_frames = COVER_FRAMES
    total_frames = duration_frames + cover_frames

    print("[8/8] 写 src/realCues.ts")
    cues_ts = ROOT / "src" / "realCues.ts"
    payload = {
        "videoSrc": "source.mp4",
        "coverBgSrc": "cover_bg.jpg",
        "coverDurationInFrames": cover_frames,
        "videoDurationInFrames": duration_frames,
        "durationInFrames": total_frames,
        "title": title,
        "hashtag": hashtag,
        "chapters": chapters,
        "cues": cues,
    }
    body = (
        "// Auto-generated by make_cues.py — do not edit by hand.\n"
        "import type { SubtitleProps } from './SubtitleWithImages';\n\n"
        "export const realProps: SubtitleProps = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + " as unknown as SubtitleProps;\n"
    )
    cues_ts.write_text(body, encoding="utf-8")

    n_imgs = len(image_for_idx)
    print(f"\n完成。{n_imgs}/{len(cues)} 段配到了图。")
    print(f"标题: 「{title}」 / Hashtag: 「{hashtag}」 / {len(chapters)} 个章节。")
    print(f"封面: {cover_frames} 帧 (用作缩略图) + 视频 {duration_frames} 帧 = 总 {total_frames} 帧")


if __name__ == "__main__":
    main()
